[itemToggle]
	gold_ring = true
	amethyst_ring = true
	diamond_ring = true
	emerald_ring = true
	flight_ring = true
	netherite_ring = true
	ring_of_life = true
	thunder_ring = true
	nether_fire = true
	freeze_ring = true
	nostalgic_butterfly_ring = true
	war_dead_badge = true
	undead_charm = true
	destroyer_badge = true
	twisted_brain = true
	corrupt_badge = true
	cursed_talisman = true
	cursed_protector = true
	cursed_totem = true
	holy_talisman = true
	holy_sword = true
	angel_heart = true
	angel_pearl = true
	demon_curse = true
	knight_shelter = true
	soul_box = true
	solar_magnet = true
	gluttony_badge = true
	magic_horseshoe = true
	bearing_stamen = true
	abyss_will_badge = true
	sands_talisman = true
	sacrificial_object = true
	deers_mercy_amulet = true
	deer_inscribed_amulet = true
	heart_of_revenge = true
	twisted_heart = true
	greedy_heart = true
	demon_heart = true
	traveler_scroll = true
	sea_god_scroll = true
	skywalker_scroll = true
	twisted_scroll = true
	emerald_bracelet = true
	life_bracelet = true
	precious_bracelet = true
	red_ruby_bracelet = true
	hidden_bracelet = true
	scarlet_bracelet = true
	charming_bracelet = true
	spirit_bracelet = true
	unowned_pendant = true
	chaotic_pendant = true
	shadow_pendant = true
	star_necklace = true
	cross_necklace = true
	gallop_necklace = true
	fang_necklace = true
	precious_necklace = true
	holy_necklace = true
	heirloom_necklace = true
	emerald_necklace = true
	ender_protector = true
	red_heart_necklace = true
	lock_of_abyss = true
	spirit_necklace = true
	treasure_hunter_necklace = true
	forest_cloak = true
	sea_god_crown = true
	prayer_crown = true
	abyss_core = true
	guardian_eye = true
	evil_eye = true
	spirit_crown = true
	sakura_hairpin = true
	yellow_duck = true
	angel_desire = true
	magic_arrow_bag = true
	flame_arrow_bag = true
	spirit_arrow_bag = true
	iron_scabbard = true
	leech_scabbard = true
	titan_scabbard = true
	twisted_scabbard = true
	catastrophe_scroll = true
	chaotic_etching = true
	origin_etching = true
	life_etching = true
	truth_etching = true
	desire_etching = true
	nihility_etching = true
	end_etching = true
