[debug]
	# 名称：调试原料
	# 描述：在JEI的原料过滤器中记录已添加和已更新的原料信息。
	# 有效值：[true, false]
	# 默认值：false
	debugIngredientsEnabled = false

	# 名称：调试界面
	# 描述：启用调试界面模式
	# 有效值：[true, false]
	# 默认值：false
	debugGuis = false

	# 名称：调试输入
	# 描述：启用调试输入模式
	# 有效值：[true, false]
	# 默认值：false
	debugInputs = false

	# 名称：调试信息提示框
	# 描述：启用高级提示框时，在原料提示框中添加调试信息。
	# 有效值：[true, false]
	# 默认值：false
	debugInfoTooltipsEnabled = false

	# 名称：日志搜索树统计信息
	# 描述：记录用于搜索的后缀树信息，以帮助调试JEI。
	# 有效值：[true, false]
	# 默认值：false
	logSuffixTreeStats = false


