#Avaritia Common Config
[blocks]
	#The blocks near the infinity blocks are the brightest
	"Is Infinity Light" = false

[tools]
	#Whether to merge matter cluster
	"Is Merge Matter Cluster" = true
	#Range damage value of the right key of Infinity sword
	# Default: 10000
	# Range: 100 ~ 100000
	"Sword Range Damage" = 10000
	#Infinity sword right click attack range
	# Default: 32
	# Range: 8 ~ 64
	"Sword Attack Range" = 32
	#Does the right key range attack of endless sword attack neutral creatures
	"Is Sword Damage Animal" = false
	#Does the right key spawn lightning with range of attack
	"Is Sword Cause Lightning" = false
	#Does the right key cause infinity damage
	"Is Sword Cause Endless damage" = true
	#Infinity bow scattering light arrow damage
	# Default: 10000
	# Range: 100 ~ 100000
	"Sub Arrow Damage" = 10000
	#Chain number of endless axe cutting trees
	# Default: 64
	# Range: 16 ~ 128
	"Axe Chain Count" = 64
	#The range of Infinity PickAxe can break
	# Default: 8
	# Range: 2 ~ 32
	"PickAxe Break Range" = 8
	#The range of Infinity Shovel can break
	# Default: 8
	# Range: 2 ~ 32
	"Shovel Break Range" = 8
	#Singularity default time required
	# Default: 240
	# Range: > 1
	"Singularity Time Required" = 240
	#Growth soul farmland rate
	# Default: 0.8
	# Range: 0.0 ~ 1.0
	"Growth soul farmland rate" = 0.8
	#Damage of BladeSlash for Crystal Sword
	# Default: 200
	# Range: > 0
	"BladeSlash Damage" = 200
	#Radius of BladeSlash for Crystal Sword
	# Default: 10
	# Range: 5 ~ 100
	"BladeSlash Radius" = 10

		[tools.config.avaritia]
			#config.avaritia.is_sword_attack_item_entity.tooltip
			is_sword_attack_item_entity = false
			#config.avaritia.is_sword_attack_projectile.tooltip
			is_sword_attack_projectile = false

[emc]
	#Emc of Neutron Pile
	# Default: 512
	# Range: > 0
	"Neutron Pile Emc" = 512
	#Emc of Blaze Cube
	# Default: 30568
	# Range: > 0
	"Blaze Cube Emc" = 30568
	#Emc of Totem Of Undying
	# Default: 1000
	# Range: > 0
	"Vanilla Totem Emc" = 1000

		[emc.config.avaritia]
			#config.avaritia.enable_projecte_singularity_count_boost.tooltip
			enable_projecte_singularity_count_boost = true

[channel]
	#
	# Default: 1
	# Range: 1 ~ 40
	"FastUpdate Rate" = 1
	#
	# Default: 40
	# Range: 20 ~ 1200
	"FullUpdate Rate" = 40

		[channel.config.avaritia]
			#config.avaritia.max_channels_pre_player.tooltip
			# Default: 16
			# Range: 4 ~ 64
			max_channels_pre_player = 16
			#config.avaritia.max_public_channels.tooltip
			# Default: 128
			# Range: 32 ~ 1024
			max_public_channels = 128

[misc]
	#For develop
	"Use Advance Tooltips" = false
	#The range of Endless ItemEntity
	# Default: 1000.0
	# Range: 1.0 ~ 10000.0
	"Endless ItemEntity Range" = 1000.0
	#The speed of Endless ItemEntity
	# Default: 3.0
	# Range: 1.0 ~ 10.0
	"Endless ItemEntity Speed" = 3.0
	#Infinity Elytra Flying Speed
	# Default: 1.5
	# Range: 1.0 ~ 10.0
	"Infinity Elytra Flying Speed" = 1.5
	#Infinity Elytra Flying Range Damage
	# Default: 100.0
	# Range: 0.0 ~ 10000.0
	"Infinity Elytra Flying Range Damage" = 100.0
	#Infinity Armor Night Vision
	"Infinity Open or Off Night Vision" = true

		[misc.config.avaritia]
			#config.avaritia.boot_speed_base.tooltip
			# Default: 0.1
			# Range: 0.01 ~ 1.0
			boot_speed_base = 0.1
			#config.avaritia.boot_speed_flying_multiplier.tooltip
			# Default: 1.1
			# Range: 0.1 ~ 5.0
			boot_speed_flying_multiplier = 1.1
			#config.avaritia.boot_speed_swimming_multiplier.tooltip
			# Default: 1.2
			# Range: 0.1 ~ 5.0
			boot_speed_swimming_multiplier = 1.2
			#config.avaritia.boot_speed_sneaking_multiplier
			# Default: 0.1
			# Range: 0.01 ~ 1.0
			boot_speed_sneaking_multiplier = 0.1
			#config.avaritia.boot_speed_backward_multiplier.tooltip
			# Default: 0.25
			# Range: 0.01 ~ 1.0
			boot_speed_backward_multiplier = 0.25
			#config.avaritia.boot_speed_strafing_multiplier
			# Default: 0.45
			# Range: 0.01 ~ 1.0
			boot_speed_strafing_multiplier = 0.45
			#config.avaritia.boot_speed_sprinting_multiplier
			# Default: 0.2
			# Range: 0.01 ~ 1.0
			boot_speed_sprinting_multiplier = 0.2
