#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Sep 12 19:15:44 CST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=0
shaderPack=MakeUp-UltraFast-9.5c.zip
