#Lightload core startup optimization settings
#Sat Jul 25 19:20:44 CST 2026
deferRemoteConfigDownloads=true
parallelJarJarMetadata=true
runtimeTransformerPatches=true
jarJarThreads=4
showLoadingTime=true
enabled=true
cacheResourceRoutes=false
mixinTargetIndex=true
maxContentCacheMiB=256
isolateModdedResourceReloadFailures=true
deferYaclImagePreload=true
parallelResourceLookup=true
aggressiveStartup=true
isolatedResourceReloadListenerPatterns=*
connectorCompatibilityMode=true
maxExistenceCacheMiB=256
lightspeedModernFixInterop=true
oculusPathValidationPatch=true
optimizationProfile=auto
cacheResourceContent=false
parallelLookupMinPacks=16
maxCachedResourceKiB=1024
persistentCache=true
voxelShapeCache=true
cacheResourceExistence=true
earlyAgent=true
profiling=true
forgeRegistryLookupCache=true
memoryCache=true
lazyBlockStateCache=true
