
[sweeper_maid-common-config]
	#If 0, disable item sweeping. If > 0, cool down (in seconds) between two item sweeping.
	#Range: 0 ~ 360000
	ITEM_SWEEP_INTERVAL = 600
	#Item overload in a chunk. If exceeded, a warning message will be sent.
	#Range: 1 ~ 6400000
	ITEM_OVERLOAD_THRESHOLD = 640
	#Message to be sent when item overload threshold is exceeded. "$1" stands for chunk X position, "$2" stands for chunk Z position, and "$3" stands for item count.
	OVERLOAD_MESSAGE = "[Sweeper Maid]: The number of dropped items in the region ($1, $2) is too large, with a total of $3 items!"
	#Other entities of types will be killed when cleaning, e.g. arrows. You can also kill mobs or even players by setting this.
	EXTRA_ENTITY_TYPES = ["minecraft:arrow", "minecraft:spectral_arrow", "oceanworld:drip_ice"]
	#Items in this list will never be cleaned and will be kept as item entity until it disappear.
	ITEM_WHITELIST = ["minecraft:nether_star", "minecraft:heavy_core"]
	#Items in this list will be cleaned but not added to the dustbin.
	ITEM_BLACKLIST = ["minecraft:cobblestone", "minecraft:sand"]
	#What message will be sent to players when there's 15s, 30s and 60s left to sweep. "$1" stands for the remaining time (in seconds).
	MESSAGE_BEFORE_SWEEP_15_30_60 = "[Sweeper Maid]: I'll sweep the floor in $1 seconds!"
	#What message will be sent to players when there's 1s~10s left to sweep. "$1" stands for the remaining time (in seconds).
	MESSAGE_BEFORE_SWEEP_1_10 = "[Sweeper Maid]: I'll sweep the floor in $1 seconds!"
	#What message will be sent to players after a sweep. "$1" stands for the number of killed dropped items, "$2" stands for the number of killed entities, and "$3" stands for the number of blacklisted items.
	MESSAGE_AFTER_SWEEP = "[Sweeper Maid]: $1 dropped items, $2 unnecessary entities and $3 blacklist items are cleaned during this sweeping."
	#What message will be sent to players when open a wrong dustbin.
	MESSAGE_WRONG_DUSTBIN = "[Sweeper Maid]: Wrong dustbin."
	#Name of dustbins.
	DUSTBIN_NAME = "Dustbin "
	#Count of dustbins
	#Range: 1 ~ 64
	DUSTBIN_COUNT = 64
	#What chat message will be sent to players after a sweep. Command will be appended to the end of the chat message.
	CHAT_MESSAGE_AFTER_SWEEP = "[Sweeper Maid]: Anything's missing? Let's checkout the dustbin:"
	#Permission level of a player to open the dustbin.
	#Range: 0 ~ 4
	PERMISSION_LEVEL_DUSTBIN = 0
	#Permission level of a player to clean immediately.
	#Range: 0 ~ 4
	PERMISSION_LEVEL_CLEAN = 2

